#!/usr/bin/env python3
"""
OCC Outreach Enrichment Pipeline

Takes an Evaboot CSV export and enriches each lead with:
1. Company website scraping (homepage text)
2. Personalized icebreaker generated by DeepSeek

Input: Evaboot CSV (name, title, company, email, linkedin_url, company_website...)
Output: Instantly-ready CSV with personalization column

Usage:
  python3 enrich-leads.py input.csv --max 50 --provider deepseek
"""

import csv
import json
import os
import re
import sys
import time
import urllib.request
import urllib.error
from html.parser import HTMLParser
from pathlib import Path

# --- Configuration ---
def _load_api_key():
    """Load DeepSeek API key from environment or .env file."""
    key = os.environ.get("DEEPSEEK_API_KEY", "")
    if key:
        return key
    env_paths = [
        Path.home() / ".hermes" / ".env",
        Path.home() / ".env",
    ]
    for p in env_paths:
        if p.exists():
            for line in p.read_text().splitlines():
                if line.startswith("DEEPSEEK_API_KEY="):
                    val = line.split("=", 1)[1]
                    # Strip whitespace and surrounding quotes
                    return val.strip().strip("'").strip('"')
    return ""

DEEPSEEK_API_KEY = _load_api_key()
DEEPSEEK_BASE = "https://api.deepseek.com/v1/chat/completions"
DEEPSEEK_MODEL = "deepseek-chat"
REQUEST_DELAY = 2  # seconds between requests
MAX_WEBSITE_CHARS = 3000
TIMEOUT = 15


# --- HTML Text Extractor ---
class TextExtractor(HTMLParser):
    def __init__(self):
        super().__init__()
        self.text = []
        self.skip = False

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style", "nav", "footer", "header"):
            self.skip = True

    def handle_endtag(self, tag):
        if tag in ("script", "style", "nav", "footer", "header"):
            self.skip = False

    def handle_data(self, data):
        if not self.skip:
            t = data.strip()
            if t:
                self.text.append(t)

    def get_text(self):
        return " ".join(self.text)


def scrape_website(url):
    """Scrape visible text from a website homepage."""
    if not url or not url.startswith("http"):
        return ""
    try:
        req = urllib.request.Request(url, headers={
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
        })
        resp = urllib.request.urlopen(req, timeout=TIMEOUT)
        html = resp.read().decode("utf-8", errors="ignore")
        extractor = TextExtractor()
        extractor.feed(html)
        text = extractor.get_text()
        # Clean whitespace
        text = re.sub(r'\s+', ' ', text).strip()
        return text[:MAX_WEBSITE_CHARS]
    except Exception as e:
        return ""


def generate_icebreaker(name, title, company, linkedin_headline, website_text):
    """Use DeepSeek to generate a personalized icebreaker."""
    if not DEEPSEEK_API_KEY:
        return "[DeepSeek API key not configured]"

    prompt = f"""You are writing a cold email icebreaker for an outreach campaign.

The product is One Click Coaching — AI-powered sales call scoring that reinforces sales methodology (Sandler, Challenger, SPIN, MEDDIC) after training. Target buyers are VP Sales, Sales Directors, Sales Managers at B2B companies with 5-50 reps.

Prospect:
- Name: {name}
- Title: {title}
- Company: {company}
- LinkedIn headline: {linkedin_headline or 'Not available'}
- Company website content: {website_text[:1500] if website_text else 'Not available'}

Write ONE icebreaker sentence (max 2 sentences, under 40 words) that:
1. References something SPECIFIC about this person's role, company, or industry
2. Shows you did your research
3. Creates a natural bridge to the problem of sales training drift / coaching reinforcement
4. Does NOT mention the product
5. Does NOT use generic flattery like "impressive background"

Example good icebreakers:
"I noticed [Company] just expanded the sales team — scaling methodology reinforcement is brutal at that inflection point."
"Your team runs Sandler, and I'd bet the gap between the training room and Monday morning looks familiar."
"With [X] reps and a new [vertical/region] push, I'm guessing coaching consistency is becoming a real constraint."

Return ONLY the icebreaker text. No quotes. No commentary."""

    try:
        data = json.dumps({
            "model": "deepseek-chat",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 100,
            "temperature": 1.0,
        }).encode()

        req = urllib.request.Request(DEEPSEEK_BASE, data=data, headers={
            "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
            "Content-Type": "application/json",
        })
        resp = urllib.request.urlopen(req, timeout=30)
        result = json.loads(resp.read())
        icebreaker = result["choices"][0]["message"]["content"].strip()
        # Remove quotes if present
        icebreaker = icebreaker.strip('"').strip("'")
        return icebreaker
    except Exception as e:
        return f"[Error generating: {str(e)[:80]}]"


def enrich_csv(input_path, output_path=None, max_leads=None, skip_scrape=False):
    """Main enrichment pipeline."""
    if not output_path:
        p = Path(input_path)
        output_path = str(p.parent / f"{p.stem}_enriched{p.suffix}")

    rows = []
    with open(input_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if max_leads:
        rows = rows[:max_leads]

    print(f"Processing {len(rows)} leads...")
    print(f"Website scraping: {'OFF' if skip_scrape else 'ON'}")
    print(f"DeepSeek enrichment: {'ON' if DEEPSEEK_API_KEY else 'OFF — DEEPSEEK_API_KEY not set'}")
    print()

    fieldnames = list(rows[0].keys()) + ["website_text", "icebreaker"]

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for i, row in enumerate(rows):
            name = row.get("firstName", "") + " " + row.get("lastName", "")
            name = name.strip()
            title = row.get("title", "")
            company = row.get("company", "")
            linkedin_headline = row.get("headline", "")
            website = row.get("website", "") or row.get("companyWebsite", "") or row.get("company_url", "")

            print(f"[{i+1}/{len(rows)}] {name} — {title} at {company}")

            # Scrape website
            website_text = ""
            if website and not skip_scrape:
                website_text = scrape_website(website)
                chars = len(website_text)
                print(f"  Website: {chars} chars scraped from {website[:60]}")

            # Generate icebreaker
            icebreaker = ""
            if DEEPSEEK_API_KEY:
                icebreaker = generate_icebreaker(
                    name, title, company, linkedin_headline, website_text
                )
                print(f"  Icebreaker: {icebreaker[:120]}")

            row["website_text"] = website_text
            row["icebreaker"] = icebreaker
            writer.writerow(row)

            if i < len(rows) - 1:
                time.sleep(REQUEST_DELAY)

    print(f"\nDone. Output: {output_path}")
    return output_path


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Enrich Evaboot CSV with website scraping and AI icebreakers")
    parser.add_argument("input", help="Evaboot CSV file")
    parser.add_argument("--output", help="Output CSV path")
    parser.add_argument("--max", type=int, help="Max leads to process")
    parser.add_argument("--no-scrape", action="store_true", help="Skip website scraping")
    args = parser.parse_args()

    if not DEEPSEEK_API_KEY:
        print("WARNING: DEEPSEEK_API_KEY not set. Icebreaker generation will be skipped.")
        print("Set it with: export DEEPSEEK_API_KEY=your_key")
        print()

    enrich_csv(args.input, args.output, args.max, args.no_scrape)
